ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }

    application {
        modules = [ com.vocabmaxxing.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/vocabmaxxing"
    url = ${?DATABASE_URL}
    user = "postgres"
    user = ${?DATABASE_USER}
    password = "postgres123"
    password = ${?DATABASE_PASSWORD}
}

ai {
    apiKey = ""
    apiKey = ${?AI_API_KEY}
    baseUrl = "https://api.openai.com/v1/chat/completions"
    baseUrl = ${?AI_BASE_URL}
    model = "gpt-4o-mini"
    model = ${?AI_MODEL}
}
